const POKEMON_TIERS = {
    tier0: [
        "Bayleef",
        "Beldum",
        "Blastoise",
        "Blaziken",
        "Bulbasaur",
        "Charizard",
        "Charmander",
        "Charmeleon",
        "Chikorita",
        "Chimchar",
        "Combusken",
        "Croconaw",
        "Cyndaquil",
        "Dewott",
        "Eevee",
        "Emboar",
        "Empoleon",
        "Espeon",
        "Feraligatr",
        "Flareon",
        "Glaceon",
        "Grotle",
        "Grovyle",
        "Infernape",
        "Ivysaur",
        "Jolteon",
        "Leafeon",
        "Lucario",
        "Marshtomp",
        "Meganium",
        "Metagross",
        "Metang",
        "Monferno",
        "Mudkip",
        "Munchlax",
        "Oshawott",
        "Pignite",
        "Piplup",
        "Porygon",
        "Porygon-Z",
        "Porygon2",
        "Prinplup",
        "Quilava",
        "Riolu",
        "Rotom",
        "Samurott",
        "Sceptile",
        "Serperior",
        "Servine",
        "Shedinja",
        "Snivy",
        "Snorlax",
        "Squirtle",
        "Swampert",
        "Tepig",
        "Togekiss",
        "Togepi",
        "Togetic",
        "Torchic",
        "Torterra",
        "Totodile",
        "Treecko",
        "Turtwig",
        "Typhlosion",
        "Tyrogue",
        "Umbreon",
        "Vaporeon",
        "Venusaur",
        "Wartortle",
    ],
    tier1: [
        "Absol",
        "Alomomola",
        "Audino",
        "Blissey",
        "Breloom",
        "Burmy",
        "Carnivine",
        "Castform",
        "Chansey",
        "Cherrim",
        "Cherubi",
        "Combee",
        "Delcatty",
        "Drapion",
        "Drilbur",
        "Ducklett",
        "Emolga",
        "Excadrill",
        "Gulpin",
        "Kangaskhan",
        "Larvesta",
        "Minun",
        "Mothim",
        "Panpour",
        "Pansage",
        "Pansear",
        "Pinsir",
        "Plusle",
        "Scizor",
        "Scyther",
        "Shroomish",
        "Simipour",
        "Simisage",
        "Simisear",
        "Skarmory",
        "Skitty",
        "Skorupi",
        "Slaking",
        "Slakoth",
        "Spiritomb",
        "Sudowoodo",
        "Swalot",
        "Swanna",
        "Vespiquen",
        "Vigoroth",
        "Volcarona",
        "Wormadam",
    ],
    tier2: [
        "Aerodactyl",
        "Aipom",
        "Ambipom",
        "Anorith",
        "Archen",
        "Archeops",
        "Armaldo",
        "Bagon",
        "Bastiodon",
        "Bisharp",
        "Carracosta",
        "Clefable",
        "Clefairy",
        "Cloyster",
        "Corsola",
        "Cradily",
        "Cranidos",
        "Feebas",
        "Forretress",
        "Gardevoir",
        "Houndoom",
        "Houndour",
        "Kabuto",
        "Kabutops",
        "Kirlia",
        "Lapras",
        "Lileep",
        "Milotic",
        "Miltank",
        "Mr. Mime",
        "Nincada",
        "Ninjask",
        "Omanyte",
        "Omastar",
        "Pawniard",
        "Pineco",
        "Qwilfish",
        "Ralts",
        "Rampardos",
        "Relicanth",
        "Salamence",
        "Shelgon",
        "Shellder",
        "Shieldon",
        "Shuckle",
        "Tirtouga",
        "Zoroark",
        "Zorua",
    ],
    tier3: [
        "Arcanine",
        "Barboach",
        "Cacnea",
        "Cacturne",
        "Carvanha",
        "Chatot",
        "Chimecho",
        "Croagunk",
        "Cryogonal",
        "Darmanitan",
        "Darumaka",
        "Delibird",
        "Dragonair",
        "Dragonite",
        "Dratini",
        "Drifblim",
        "Drifloon",
        "Exeggcute",
        "Exeggutor",
        "Farfetch'd",
        "Finneon",
        "Furret",
        "Gabite",
        "Garchomp",
        "Gible",
        "Gligar",
        "Gliscor",
        "Growlithe",
        "Heracross",
        "Honchkrow",
        "Illumise",
        "Jynx",
        "Kecleon",
        "Ledian",
        "Ledyba",
        "Lumineon",
        "Luvdisc",
        "Magmar",
        "Magmortar",
        "Mantine",
        "Maractus",
        "Misdreavus",
        "Mismagius",
        "Murkrow",
        "Ninetales",
        "Nosepass",
        "Octillery",
        "Probopass",
        "Remoraid",
        "Sentret",
        "Seviper",
        "Sharpedo",
        "Sigilyph",
        "Skuntank",
        "Starmie",
        "Staryu",
        "Stunky",
        "Sunflora",
        "Sunkern",
        "Toxicroak",
        "Tropius",
        "Volbeat",
        "Vulpix",
        "Wailmer",
        "Wailord",
        "Whiscash",
        "Zangoose",
    ],
    tier4: [
        "Ariados",
        "Axew",
        "Bellossom",
        "Bouffalant",
        "Braviary",
        "Buneary",
        "Corphish",
        "Crawdaunt",
        "Deino",
        "Drowzee",
        "Electabuzz",
        "Electivire",
        "Flygon",
        "Fraxure",
        "Gloom",
        "Granbull",
        "Haxorus",
        "Heatmor",
        "Hoothoot",
        "Hydreigon",
        "Hypno",
        "Kricketot",
        "Kricketune",
        "Larvitar",
        "Liepard",
        "Lombre",
        "Lopunny",
        "Lotad",
        "Ludicolo",
        "Lunatone",
        "Masquerain",
        "Meowth",
        "Noctowl",
        "Oddish",
        "Pachirisu",
        "Persian",
        "Pidove",
        "Pupitar",
        "Purrloin",
        "Quagsire",
        "Rufflet",
        "Scrafty",
        "Scraggy",
        "Sneasel",
        "Snubbull",
        "Spinarak",
        "Spinda",
        "Surskit",
        "Tranquill",
        "Trapinch",
        "Tyranitar",
        "Unfezant",
        "Venomoth",
        "Venonat",
        "Vibrava",
        "Vileplume",
        "Weavile",
        "Wooper",
        "Zweilous",
    ],
    tier5: [
        "Accelgor",
        "Altaria",
        "Amoonguss",
        "Beartic",
        "Beautifly",
        "Beedrill",
        "Bellsprout",
        "Butterfree",
        "Camerupt",
        "Cascoon",
        "Caterpie",
        "Conkeldurr",
        "Cottonee",
        "Crustle",
        "Cubchoo",
        "Dustox",
        "Dwebble",
        "Eelektrik",
        "Eelektross",
        "Escavalier",
        "Ferroseed",
        "Ferrothorn",
        "Foongus",
        "Froslass",
        "Galvantula",
        "Garbodor",
        "Glalie",
        "Gurdurr",
        "Herdier",
        "Hippopotas",
        "Hippowdon",
        "Hoppip",
        "Horsea",
        "Jigglypuff",
        "Joltik",
        "Jumpluff",
        "Kakuna",
        "Karrablast",
        "Kingdra",
        "Lillipup",
        "Metapod",
        "Natu",
        "Nidoking",
        "Nidoran♂",
        "Nidorino",
        "Numel",
        "Paras",
        "Parasect",
        "Pikachu",
        "Raichu",
        "Sawk",
        "Scolipede",
        "Seadra",
        "Shelmet",
        "Silcoon",
        "Skiploom",
        "Snorunt",
        "Staraptor",
        "Staravia",
        "Starly",
        "Stoutland",
        "Swablu",
        "Swellow",
        "Taillow",
        "Teddiursa",
        "Throh",
        "Timburr",
        "Trubbish",
        "Tynamo",
        "Ursaring",
        "Venipede",
        "Victreebel",
        "Weedle",
        "Weepinbell",
        "Whimsicott",
        "Whirlipede",
        "Wigglytuff",
        "Wurmple",
        "Xatu",
    ],
    tier6: [
        "Abomasnow",
        "Abra",
        "Aggron",
        "Alakazam",
        "Ampharos",
        "Arbok",
        "Aron",
        "Beheeyem",
        "Bibarel",
        "Bidoof",
        "Blitzle",
        "Boldore",
        "Chinchou",
        "Cinccino",
        "Clamperl",
        "Cubone",
        "Diglett",
        "Ditto",
        "Dodrio",
        "Doduo",
        "Donphan",
        "Druddigon",
        "Dugtrio",
        "Duosion",
        "Durant",
        "Ekans",
        "Electrike",
        "Elgyem",
        "Fearow",
        "Flaaffy",
        "Gigalith",
        "Gorebyss",
        "Gothita",
        "Gothitelle",
        "Gothorita",
        "Grimer",
        "Grumpig",
        "Hariyama",
        "Huntail",
        "Kadabra",
        "Klang",
        "Klink",
        "Klinklang",
        "Lairon",
        "Lanturn",
        "Leavanny",
        "Lickilicky",
        "Lickitung",
        "Linoone",
        "Luxio",
        "Luxray",
        "Magcargo",
        "Makuhita",
        "Mandibuzz",
        "Manectric",
        "Mankey",
        "Mareep",
        "Marowak",
        "Mawile",
        "Mightyena",
        "Minccino",
        "Muk",
        "Munna",
        "Musharna",
        "Nidoqueen",
        "Nidoran♀",
        "Nidorina",
        "Palpitoad",
        "Patrat",
        "Pelipper",
        "Phanpy",
        "Pidgeot",
        "Pidgeotto",
        "Pidgey",
        "Ponyta",
        "Poochyena",
        "Primeape",
        "Rapidash",
        "Reuniclus",
        "Roggenrola",
        "Roselia",
        "Roserade",
        "Sableye",
        "Seismitoad",
        "Sewaddle",
        "Shinx",
        "Slugma",
        "Snover",
        "Solosis",
        "Solrock",
        "Spearow",
        "Spoink",
        "Stantler",
        "Stunfisk",
        "Swadloon",
        "Swoobat",
        "Tangela",
        "Tangrowth",
        "Tympole",
        "Vanillish",
        "Vanillite",
        "Vanilluxe",
        "Vullaby",
        "Watchog",
        "Whismur",
        "Wingull",
        "Woobat",
        "Zebstrika",
        "Zigzagoon",
    ],
    tier7: [
        "Azumarill",
        "Azurill",
        "Baltoy",
        "Banette",
        "Basculin",
        "Bonsly",
        "Bronzong",
        "Bronzor",
        "Budew",
        "Buizel",
        "Chandelure",
        "Chingling",
        "Claydol",
        "Cleffa",
        "Cofagrigus",
        "Crobat",
        "Deerling",
        "Dewgong",
        "Dunsparce",
        "Dusclops",
        "Dusknoir",
        "Duskull",
        "Electrode",
        "Elekid",
        "Floatzel",
        "Frillish",
        "Gallade",
        "Gastly",
        "Gastrodon",
        "Gengar",
        "Geodude",
        "Girafarig",
        "Glameow",
        "Golbat",
        "Goldeen",
        "Golduck",
        "Golem",
        "Golett",
        "Golurk",
        "Graveler",
        "Gyarados",
        "Happiny",
        "Haunter",
        "Hitmonchan",
        "Hitmonlee",
        "Hitmontop",
        "Igglybuff",
        "Jellicent",
        "Kingler",
        "Koffing",
        "Krabby",
        "Krokorok",
        "Krookodile",
        "Lampent",
        "Lilligant",
        "Litwick",
        "Machamp",
        "Machoke",
        "Machop",
        "Magby",
        "Magikarp",
        "Magnemite",
        "Magneton",
        "Mamoswine",
        "Mantyke",
        "Marill",
        "Medicham",
        "Meditite",
        "Mienfoo",
        "Mienshao",
        "Mime Jr.",
        "Nuzleaf",
        "Onix",
        "Petilil",
        "Pichu",
        "Piloswine",
        "Politoed",
        "Poliwag",
        "Poliwhirl",
        "Poliwrath",
        "Psyduck",
        "Purugly",
        "Raticate",
        "Rattata",
        "Rhydon",
        "Rhyhorn",
        "Rhyperior",
        "Sandile",
        "Sandshrew",
        "Sandslash",
        "Sawsbuck",
        "Seaking",
        "Sealeo",
        "Seedot",
        "Seel",
        "Shellos",
        "Shiftry",
        "Shuppet",
        "Slowbro",
        "Slowking",
        "Slowpoke",
        "Smeargle",
        "Smoochum",
        "Spheal",
        "Steelix",
        "Swinub",
        "Tauros",
        "Tentacool",
        "Tentacruel",
        "Torkoal",
        "Unown",
        "Voltorb",
        "Walrein",
        "Weezing",
        "Wobbuffet",
        "Wynaut",
        "Yamask",
        "Yanma",
        "Yanmega",
        "Zubat",
    ],
    legendary: [
        "Arceus",
        "Articuno",
        "Azelf",
        "Celebi",
        "Cobalion",
        "Cresselia",
        "Darkrai",
        "Deoxys",
        "Dialga",
        "Entei",
        "Genesect",
        "Giratina",
        "Groudon",
        "Heatran",
        "Ho-Oh",
        "Jirachi",
        "Keldeo",
        "Kyogre",
        "Kyurem",
        "Landorus",
        "Latias",
        "Latios",
        "Lugia",
        "Manaphy",
        "Meloetta",
        "Mesprit",
        "Mew",
        "Mewtwo",
        "Moltres",
        "Palkia",
        "Phione",
        "Raikou",
        "Rayquaza",
        "Regice",
        "Regigigas",
        "Regirock",
        "Registeel",
        "Reshiram",
        "Shaymin",
        "Suicune",
        "Terrakion",
        "Thundurus",
        "Tornadus",
        "Uxie",
        "Victini",
        "Virizion",
        "Zapdos",
        "Zekrom",
    ],
};

const TIER_POINTS = {
    "legendary": 200,
    "tier0": 50,
    "tier1": 45,
    "tier2": 40,
    "tier3": 30,
    "tier4": 15,
    "tier5": 10,
    "tier6": 5,
    "tier7": 3
};

const METHOD_BONUS = {
    "wild": 0,
    "egg": 35,
    "safari": 10,
    "secret": 20
};

const TIER_COLORS = {
    "legendary": "#fbbf24",
    "tier0": "#ef4444",
    "tier1": "#f97316",
    "tier2": "#eab308",
    "tier3": "#84cc16",
    "tier4": "#22c55e",
    "tier5": "#14b8a6",
    "tier6": "#06b6d4",
    "tier7": "#64748b"
};

const POKEMON_SEASONS = {
    "Abomasnow": "all",
    "Abra": "all",
    "Absol": "all",
    "Accelgor": "all",
    "Aerodactyl": "all",
    "Aggron": "all",
    "Aipom": "all",
    "Alakazam": "all",
    "Alomomola": "all",
    "Altaria": "all",
    "Ambipom": "all",
    "Amoonguss": "all",
    "Ampharos": "all",
    "Anorith": "all",
    "Arbok": "all",
    "Arcanine": "all",
    "Arceus": "all",
    "Archen": "all",
    "Archeops": "all",
    "Ariados": "all",
    "Armaldo": "all",
    "Aron": "all",
    "Articuno": "all",
    "Audino": "all",
    "Axew": "all",
    "Azelf": "all",
    "Azumarill": "all",
    "Azurill": "all",
    "Bagon": "all",
    "Baltoy": "all",
    "Banette": "all",
    "Barboach": "all",
    "Basculin": "all",
    "Bastiodon": "all",
    "Bayleef": "all",
    "Beartic": "all",
    "Beautifly": "all",
    "Beedrill": "all",
    "Beheeyem": "all",
    "Beldum": "all",
    "Bellossom": "all",
    "Bellsprout": "all",
    "Bibarel": "all",
    "Bidoof": "all",
    "Bisharp": "all",
    "Blastoise": "all",
    "Blaziken": "all",
    "Blissey": "all",
    "Blitzle": "all",
    "Boldore": "all",
    "Bonsly": "all",
    "Bouffalant": "all",
    "Braviary": "all",
    "Breloom": "all",
    "Bronzong": "all",
    "Bronzor": "all",
    "Budew": "all",
    "Buizel": "all",
    "Bulbasaur": "all",
    "Buneary": "all",
    "Burmy": "all",
    "Butterfree": "all",
    "Cacnea": "all",
    "Cacturne": "all",
    "Camerupt": "all",
    "Carnivine": "all",
    "Carracosta": "all",
    "Carvanha": "all",
    "Cascoon": "all",
    "Castform": "all",
    "Caterpie": "all",
    "Celebi": "all",
    "Chandelure": "all",
    "Chansey": "all",
    "Charizard": "all",
    "Charmander": "all",
    "Charmeleon": "all",
    "Chatot": "all",
    "Cherrim": "all",
    "Cherubi": "all",
    "Chikorita": "all",
    "Chimchar": "all",
    "Chimecho": "all",
    "Chinchou": "all",
    "Chingling": "all",
    "Cinccino": "all",
    "Clamperl": "all",
    "Claydol": "all",
    "Clefable": "all",
    "Clefairy": "all",
    "Cleffa": "all",
    "Cloyster": "all",
    "Cobalion": "all",
    "Cofagrigus": "all",
    "Combee": "all",
    "Combusken": "all",
    "Conkeldurr": "all",
    "Corphish": "all",
    "Corsola": "all",
    "Cottonee": "all",
    "Cradily": "all",
    "Cranidos": "all",
    "Crawdaunt": "all",
    "Cresselia": "all",
    "Croagunk": "all",
    "Crobat": "all",
    "Croconaw": "all",
    "Crustle": "all",
    "Cryogonal": "all",
    "Cubchoo": "all",
    "Cubone": "all",
    "Cyndaquil": "all",
    "Darkrai": "all",
    "Darmanitan": "all",
    "Darumaka": "all",
    "Deerling": "all",
    "Deino": "all",
    "Delcatty": "all",
    "Delibird": "all",
    "Deoxys": "all",
    "Dewgong": "all",
    "Dewott": "all",
    "Dialga": "all",
    "Diglett": "all",
    "Ditto": "all",
    "Dodrio": "all",
    "Doduo": "all",
    "Donphan": "all",
    "Dragonair": "all",
    "Dragonite": "all",
    "Drapion": "all",
    "Dratini": "all",
    "Drifblim": "all",
    "Drifloon": "all",
    "Drilbur": "all",
    "Drowzee": "all",
    "Druddigon": "all",
    "Ducklett": "all",
    "Dugtrio": "all",
    "Dunsparce": "all",
    "Duosion": "all",
    "Durant": "all",
    "Dusclops": "all",
    "Dusknoir": "all",
    "Duskull": "all",
    "Dustox": "all",
    "Dwebble": "all",
    "Eelektrik": "all",
    "Eelektross": "all",
    "Eevee": "all",
    "Ekans": "all",
    "Electabuzz": "all",
    "Electivire": "all",
    "Electrike": "all",
    "Electrode": "all",
    "Elekid": "all",
    "Elgyem": "all",
    "Emboar": "all",
    "Emolga": "all",
    "Empoleon": "all",
    "Entei": "all",
    "Escavalier": "all",
    "Espeon": "all",
    "Excadrill": "all",
    "Exeggcute": "all",
    "Exeggutor": "all",
    "Farfetch'd": "all",
    "Fearow": "all",
    "Feebas": "all",
    "Feraligatr": "all",
    "Ferroseed": "all",
    "Ferrothorn": "all",
    "Finneon": "all",
    "Flaaffy": "all",
    "Flareon": "all",
    "Floatzel": "all",
    "Flygon": "all",
    "Foongus": "all",
    "Forretress": "all",
    "Fraxure": "all",
    "Frillish": "all",
    "Froslass": "all",
    "Furret": "all",
    "Gabite": "all",
    "Gallade": "all",
    "Galvantula": "all",
    "Garbodor": "all",
    "Garchomp": "all",
    "Gardevoir": "all",
    "Gastly": "all",
    "Gastrodon": "all",
    "Genesect": "all",
    "Gengar": "all",
    "Geodude": "all",
    "Gible": "all",
    "Gigalith": "all",
    "Girafarig": "all",
    "Giratina": "all",
    "Glaceon": "all",
    "Glalie": "all",
    "Glameow": "all",
    "Gligar": "all",
    "Gliscor": "all",
    "Gloom": "all",
    "Golbat": "all",
    "Goldeen": "all",
    "Golduck": "all",
    "Golem": "all",
    "Golett": "all",
    "Golurk": "all",
    "Gorebyss": "all",
    "Gothita": "all",
    "Gothitelle": "all",
    "Gothorita": "all",
    "Granbull": "all",
    "Graveler": "all",
    "Grimer": "all",
    "Grotle": "all",
    "Groudon": "all",
    "Grovyle": "all",
    "Growlithe": "all",
    "Grumpig": "all",
    "Gulpin": "all",
    "Gurdurr": "all",
    "Gyarados": "all",
    "Happiny": "all",
    "Hariyama": "all",
    "Haunter": "all",
    "Haxorus": "all",
    "Heatmor": "all",
    "Heatran": "all",
    "Heracross": "all",
    "Herdier": "all",
    "Hippopotas": "all",
    "Hippowdon": "all",
    "Hitmonchan": "all",
    "Hitmonlee": "all",
    "Hitmontop": "all",
    "Ho-Oh": "all",
    "Honchkrow": "all",
    "Hoothoot": "all",
    "Hoppip": "all",
    "Horsea": "all",
    "Houndoom": "all",
    "Houndour": "all",
    "Huntail": "all",
    "Hydreigon": "all",
    "Hypno": "all",
    "Igglybuff": "all",
    "Illumise": "all",
    "Infernape": "all",
    "Ivysaur": "all",
    "Jellicent": "all",
    "Jigglypuff": "all",
    "Jirachi": "all",
    "Jolteon": "all",
    "Joltik": "all",
    "Jumpluff": "all",
    "Jynx": "all",
    "Kabuto": "all",
    "Kabutops": "all",
    "Kadabra": "all",
    "Kakuna": "all",
    "Kangaskhan": "all",
    "Karrablast": "all",
    "Kecleon": "all",
    "Keldeo": "all",
    "Kingdra": "all",
    "Kingler": "all",
    "Kirlia": "all",
    "Klang": "all",
    "Klink": "all",
    "Klinklang": "all",
    "Koffing": "all",
    "Krabby": "all",
    "Kricketot": "all",
    "Kricketune": "all",
    "Krokorok": "all",
    "Krookodile": "all",
    "Kyogre": "all",
    "Kyurem": "all",
    "Lairon": "all",
    "Lampent": "all",
    "Landorus": "all",
    "Lanturn": "all",
    "Lapras": "all",
    "Larvesta": "all",
    "Larvitar": "all",
    "Latias": "all",
    "Latios": "all",
    "Leafeon": "all",
    "Leavanny": "all",
    "Ledian": "all",
    "Ledyba": "all",
    "Lickilicky": "all",
    "Lickitung": "all",
    "Liepard": "all",
    "Lileep": "all",
    "Lilligant": "all",
    "Lillipup": "all",
    "Linoone": "all",
    "Litwick": "all",
    "Lombre": "all",
    "Lopunny": "all",
    "Lotad": "all",
    "Lucario": "all",
    "Ludicolo": "all",
    "Lugia": "all",
    "Lumineon": "all",
    "Lunatone": "all",
    "Luvdisc": "all",
    "Luxio": "all",
    "Luxray": "all",
    "Machamp": "all",
    "Machoke": "all",
    "Machop": "all",
    "Magby": "all",
    "Magcargo": "all",
    "Magikarp": "all",
    "Magmar": "all",
    "Magmortar": "all",
    "Magnemite": "all",
    "Magneton": "all",
    "Makuhita": "all",
    "Mamoswine": "all",
    "Manaphy": "all",
    "Mandibuzz": "all",
    "Manectric": "all",
    "Mankey": "all",
    "Mantine": "all",
    "Mantyke": "all",
    "Maractus": "all",
    "Mareep": "all",
    "Marill": "all",
    "Marowak": "all",
    "Marshtomp": "all",
    "Masquerain": "all",
    "Mawile": "all",
    "Medicham": "all",
    "Meditite": "all",
    "Meganium": "all",
    "Meloetta": "all",
    "Meowth": "all",
    "Mesprit": "all",
    "Metagross": "all",
    "Metang": "all",
    "Metapod": "all",
    "Mew": "all",
    "Mewtwo": "all",
    "Mienfoo": "all",
    "Mienshao": "all",
    "Mightyena": "all",
    "Milotic": "all",
    "Miltank": "all",
    "Mime Jr.": "all",
    "Minccino": "all",
    "Minun": "all",
    "Misdreavus": "all",
    "Mismagius": "all",
    "Moltres": "all",
    "Monferno": "all",
    "Mothim": "all",
    "Mr. Mime": "all",
    "Mudkip": "all",
    "Muk": "all",
    "Munchlax": "all",
    "Munna": "all",
    "Murkrow": "all",
    "Musharna": "all",
    "Natu": "all",
    "Nidoking": "all",
    "Nidoqueen": "all",
    "Nidoran♀": "all",
    "Nidoran♂": "all",
    "Nidorina": "all",
    "Nidorino": "all",
    "Nincada": "all",
    "Ninetales": "all",
    "Ninjask": "all",
    "Noctowl": "all",
    "Nosepass": "all",
    "Numel": "all",
    "Nuzleaf": "all",
    "Octillery": "all",
    "Oddish": "all",
    "Omanyte": "all",
    "Omastar": "all",
    "Onix": "all",
    "Oshawott": "all",
    "Pachirisu": "all",
    "Palkia": "all",
    "Palpitoad": "all",
    "Panpour": "all",
    "Pansage": "all",
    "Pansear": "all",
    "Paras": "all",
    "Parasect": "all",
    "Patrat": "all",
    "Pawniard": "all",
    "Pelipper": "all",
    "Persian": "all",
    "Petilil": "all",
    "Phanpy": "all",
    "Phione": "all",
    "Pichu": "all",
    "Pidgeot": "all",
    "Pidgeotto": "all",
    "Pidgey": "all",
    "Pidove": "all",
    "Pignite": "all",
    "Pikachu": "all",
    "Piloswine": "all",
    "Pineco": "all",
    "Pinsir": "all",
    "Piplup": "all",
    "Plusle": "all",
    "Politoed": "all",
    "Poliwag": "all",
    "Poliwhirl": "all",
    "Poliwrath": "all",
    "Ponyta": "all",
    "Poochyena": "all",
    "Porygon": "all",
    "Porygon-Z": "all",
    "Porygon2": "all",
    "Primeape": "all",
    "Prinplup": "all",
    "Probopass": "all",
    "Psyduck": "all",
    "Pupitar": "all",
    "Purrloin": "all",
    "Purugly": "all",
    "Quagsire": "all",
    "Quilava": "all",
    "Qwilfish": "all",
    "Raichu": "all",
    "Raikou": "all",
    "Ralts": "all",
    "Rampardos": "all",
    "Rapidash": "all",
    "Raticate": "all",
    "Rattata": "all",
    "Rayquaza": "all",
    "Regice": "all",
    "Regigigas": "all",
    "Regirock": "all",
    "Registeel": "all",
    "Relicanth": "all",
    "Remoraid": "all",
    "Reshiram": "all",
    "Reuniclus": "all",
    "Rhydon": "all",
    "Rhyhorn": "all",
    "Rhyperior": "all",
    "Riolu": "all",
    "Roggenrola": "all",
    "Roselia": "all",
    "Roserade": "all",
    "Rotom": "all",
    "Rufflet": "all",
    "Sableye": "all",
    "Salamence": "all",
    "Samurott": "all",
    "Sandile": "all",
    "Sandshrew": "all",
    "Sandslash": "all",
    "Sawk": "all",
    "Sawsbuck": "all",
    "Sceptile": "all",
    "Scizor": "all",
    "Scolipede": "all",
    "Scrafty": "all",
    "Scraggy": "all",
    "Scyther": "all",
    "Seadra": "all",
    "Seaking": "all",
    "Sealeo": "all",
    "Seedot": "all",
    "Seel": "all",
    "Seismitoad": "all",
    "Sentret": "all",
    "Serperior": "all",
    "Servine": "all",
    "Seviper": "all",
    "Sewaddle": "all",
    "Sharpedo": "all",
    "Shaymin": "all",
    "Shedinja": "all",
    "Shelgon": "all",
    "Shellder": "all",
    "Shellos": "all",
    "Shelmet": "all",
    "Shieldon": "all",
    "Shiftry": "all",
    "Shinx": "all",
    "Shroomish": "all",
    "Shuckle": "all",
    "Shuppet": "all",
    "Sigilyph": "all",
    "Silcoon": "all",
    "Simipour": "all",
    "Simisage": "all",
    "Simisear": "all",
    "Skarmory": "all",
    "Skiploom": "all",
    "Skitty": "all",
    "Skorupi": "all",
    "Skuntank": "all",
    "Slaking": "all",
    "Slakoth": "all",
    "Slowbro": "all",
    "Slowking": "all",
    "Slowpoke": "all",
    "Slugma": "all",
    "Smeargle": "all",
    "Smoochum": "all",
    "Sneasel": "all",
    "Snivy": "all",
    "Snorlax": "all",
    "Snorunt": "all",
    "Snover": "all",
    "Snubbull": "all",
    "Solosis": "all",
    "Solrock": "all",
    "Spearow": "all",
    "Spheal": "all",
    "Spinarak": "all",
    "Spinda": "all",
    "Spiritomb": "all",
    "Spoink": "all",
    "Squirtle": "all",
    "Stantler": "all",
    "Staraptor": "all",
    "Staravia": "all",
    "Starly": "all",
    "Starmie": "all",
    "Staryu": "all",
    "Steelix": "all",
    "Stoutland": "all",
    "Stunfisk": "all",
    "Stunky": "all",
    "Sudowoodo": "all",
    "Suicune": "all",
    "Sunflora": "all",
    "Sunkern": "all",
    "Surskit": "all",
    "Swablu": "all",
    "Swadloon": "all",
    "Swalot": "all",
    "Swampert": "all",
    "Swanna": "all",
    "Swellow": "all",
    "Swinub": "all",
    "Swoobat": "all",
    "Taillow": "all",
    "Tangela": "all",
    "Tangrowth": "all",
    "Tauros": "all",
    "Teddiursa": "all",
    "Tentacool": "all",
    "Tentacruel": "all",
    "Tepig": "all",
    "Terrakion": "all",
    "Throh": "all",
    "Thundurus": "all",
    "Timburr": "all",
    "Tirtouga": "all",
    "Togekiss": "all",
    "Togepi": "all",
    "Togetic": "all",
    "Torchic": "all",
    "Torkoal": "all",
    "Tornadus": "all",
    "Torterra": "all",
    "Totodile": "all",
    "Toxicroak": "all",
    "Tranquill": "all",
    "Trapinch": "all",
    "Treecko": "all",
    "Tropius": "all",
    "Trubbish": "all",
    "Turtwig": "all",
    "Tympole": "all",
    "Tynamo": "all",
    "Typhlosion": "all",
    "Tyranitar": "all",
    "Tyrogue": "all",
    "Umbreon": "all",
    "Unfezant": "all",
    "Unown": "all",
    "Ursaring": "all",
    "Uxie": "all",
    "Vanillish": "all",
    "Vanillite": "all",
    "Vanilluxe": "all",
    "Vaporeon": "all",
    "Venipede": "all",
    "Venomoth": "all",
    "Venonat": "all",
    "Venusaur": "all",
    "Vespiquen": "all",
    "Vibrava": "all",
    "Victini": "all",
    "Victreebel": "all",
    "Vigoroth": "all",
    "Vileplume": "all",
    "Virizion": "all",
    "Volbeat": "all",
    "Volcarona": "all",
    "Voltorb": "all",
    "Vullaby": "all",
    "Vulpix": "all",
    "Wailmer": "all",
    "Wailord": "all",
    "Walrein": "all",
    "Wartortle": "all",
    "Watchog": "all",
    "Weavile": "all",
    "Weedle": "all",
    "Weepinbell": "all",
    "Weezing": "all",
    "Whimsicott": "all",
    "Whirlipede": "all",
    "Whiscash": "all",
    "Whismur": "all",
    "Wigglytuff": "all",
    "Wingull": "all",
    "Wobbuffet": "all",
    "Woobat": "all",
    "Wooper": "all",
    "Wormadam": "all",
    "Wurmple": "all",
    "Wynaut": "all",
    "Xatu": "all",
    "Yamask": "all",
    "Yanma": "all",
    "Yanmega": "all",
    "Zangoose": "all",
    "Zapdos": "all",
    "Zebstrika": "all",
    "Zekrom": "all",
    "Zigzagoon": "all",
    "Zoroark": "all",
    "Zorua": "all",
    "Zubat": "all",
    "Zweilous": "all",
};

const SEASON_LABELS = {
    "all": "Todas",
    "spring": "Primavera",
    "summer": "Verano",
    "autumn": "Otono",
    "winter": "Invierno"
};

function getPokemonTier(pokemonName) {
    var ov = getPokemonOverride(pokemonName.toLowerCase());
    if (ov && ov.tier) {
        return ov.tier;
    }
    const name = pokemonName.toLowerCase();
    for (const [tier, list] of Object.entries(POKEMON_TIERS)) {
        if (list.some(p => p.toLowerCase() === name)) {
            return tier;
        }
    }
    return null;
}

var pokemonOverrides = {};

function getPokemonOverride(key) {
    if (pokemonOverrides[key] !== undefined) return pokemonOverrides[key];
    for (var k in pokemonOverrides) {
        if (k.toLowerCase() === key) return pokemonOverrides[k];
    }
    return undefined;
}

function getPokemonSeasons(pokemonName) {
    var ov = getPokemonOverride(pokemonName.toLowerCase());
    if (ov && ov.seasons !== undefined) {
        if (!ov.seasons || ov.seasons === "all") return ["all"];
        return ov.seasons.split(',');
    }
    var staticSeason = POKEMON_SEASONS[pokemonName] || "all";
    return [staticSeason];
}

function getPokemonSeason(pokemonName) {
    return getPokemonSeasons(pokemonName)[0];
}

function getPokemonRoutes(pokemonName) {
    var ov = getPokemonOverride(pokemonName.toLowerCase());
    if (ov && ov.routes) return ov.routes;
    return {};
}

function getSeasonLabel(season) {
    return SEASON_LABELS[season] || "Todas";
}

function getSeasonBadgeHTML(pokemonName) {
    var seasons = getPokemonSeasons(pokemonName);
    if (seasons.length === 0) return "";
    if (seasons.length === 1 && seasons[0] === "all") return '<span class="season-badge">🌿 Todas</span>';
    var icons = {spring:"🌸", summer:"☀️", autumn:"🍂", winter:"❄️"};
    var labels = {spring:"Primavera", summer:"Verano", autumn:"Otoño", winter:"Invierno"};
    return seasons.map(function(s) {
        return '<span class="season-badge season-badge-' + s + '">' + (icons[s]||"") + " " + (labels[s]||s) + "</span>";
    }).join(" ");
}

function calculatePoints(tier, method, isAlpha, isSecret) {
    const normalizedTier = tier && !tier.startsWith('tier') && tier !== 'legendary' && tier !== 'alpha' ? 'tier' + tier : tier;
    let base = isAlpha ? 75 : (TIER_POINTS[normalizedTier] || TIER_POINTS[tier] || 0);
    if (method === "egg") base = Math.max(35, base);
    if (method === "safari") base += 10;
    if (isSecret) base += 20;
    return base;
}

function getEvolutionLine(pokemonName) {
    const key = pokemonName.toLowerCase();
    for (const [name, line] of Object.entries(EVOLUTION_LINES)) {
        if (name.toLowerCase() === key) return line;
    }
    return pokemonName;
}

function calculateTeamScore(allTargets) {
    const caught = allTargets.filter(t => t.caught);
    if (caught.length === 0) return { total: 0, base: 0, methodBonus: 0, uniqueBonus: 0, duplicateCount: 0, perPlayer: {}, uniqueLines: [], caughtCount: 0 };
    let base = 0, methodBonus = 0;
    const perPlayer = {}, allLines = new Set(), pokemonCatchers = {};
    let duplicateCount = 0;
    caught.forEach(t => {
        const key = t.pokemon_name.toLowerCase();
        if (!pokemonCatchers[key]) pokemonCatchers[key] = [];
        pokemonCatchers[key].push(t);
    });
    caught.forEach(t => {
        const line = getEvolutionLine(t.pokemon_name);
        const method = t.method || 'wild';
        const key = t.pokemon_name.toLowerCase();
        const isDuplicate = pokemonCatchers[key].length > 1 && pokemonCatchers[key][0] !== t;
        let pts;
        if (isDuplicate) {
            pts = t.is_alpha ? 35 : 1;
            duplicateCount++;
        } else {
            let b = t.is_alpha ? 75 : (TIER_POINTS[t.tier] || 0);
            if (method === 'egg') b = Math.max(35, b);
            if (method === 'safari') b += 10;
            if (t.is_secret) b += 20;
            pts = b;
        }
        const rawBase = t.is_alpha ? 75 : (TIER_POINTS[t.tier] || 0);
        base += isDuplicate ? pts : rawBase;
        if (!isDuplicate) methodBonus += (pts - rawBase);
        allLines.add(line);
        if (!perPlayer[t.user_id]) perPlayer[t.user_id] = [];
        perPlayer[t.user_id].push({ ...t, line, points: pts, isDuplicate });
    });
    const uniqueLines = [...allLines];
    return { total: base + methodBonus + uniqueLines.length * 8, base, methodBonus, uniqueBonus: uniqueLines.length * 8, duplicateCount, uniqueLines, caughtCount: caught.length };
}

function calculatePlayerScore(playerTargets, allTargets) {
    const caught = playerTargets.filter(t => t.caught);
    if (caught.length === 0) return { total: 0, base: 0, methodBonus: 0, uniqueBonus: 0, caughtCount: 0 };
    const teamCaught = allTargets.filter(t => t.caught);
    const teamLines = new Set();
    teamCaught.forEach(t => teamLines.add(getEvolutionLine(t.pokemon_name)));
    const pokemonCatchers = {};
    teamCaught.forEach(t => {
        const key = t.pokemon_name.toLowerCase();
        if (!pokemonCatchers[key]) pokemonCatchers[key] = [];
        pokemonCatchers[key].push(t);
    });
    let base = 0, methodBonus = 0;
    caught.forEach(t => {
        const method = t.method || 'wild';
        const key = t.pokemon_name.toLowerCase();
        const isDuplicate = pokemonCatchers[key] && pokemonCatchers[key].length > 1;
        let pts;
        if (isDuplicate) {
            pts = t.is_alpha ? 35 : 1;
        } else {
            let b = t.is_alpha ? 75 : (TIER_POINTS[t.tier] || 0);
            if (method === 'egg') b = Math.max(35, b);
            if (method === 'safari') b += 10;
            if (t.is_secret) b += 20;
            pts = b;
        }
        const rawBase = t.is_alpha ? 75 : (TIER_POINTS[t.tier] || 0);
        base += isDuplicate ? pts : rawBase;
        if (!isDuplicate) methodBonus += (pts - rawBase);
    });
    let uniqueBonus = 0;
    const playerLines = new Set();
    caught.forEach(t => playerLines.add(getEvolutionLine(t.pokemon_name)));
    playerLines.forEach(line => { if (teamLines.has(line)) uniqueBonus += 8; });
    return { total: base + methodBonus + uniqueBonus, base, methodBonus, uniqueBonus, caughtCount: caught.length };
}

function searchPokemon(query) {
    if (!query || query.length < 1) return [];
    const q = query.toLowerCase();
    const results = [], seen = new Set();
    for (const [tier, list] of Object.entries(POKEMON_TIERS)) {
        for (const name of list) {
            if (name.toLowerCase().includes(q) && !seen.has(name.toLowerCase())) {
                seen.add(name.toLowerCase());
                results.push({ name, tier, points: TIER_POINTS[tier] || 0 });
            }
        }
    }
    results.sort((a, b) => b.points - a.points);
    return results.slice(0, 30);
}

function suggestPokemon(query) {
    return searchPokemon(query);
}

function esc(str) {
    if (!str) return '';
    const d = document.createElement('div');
    d.textContent = str;
    return d.innerHTML;
}

function getRouteChipsHTML(pokemonName) {
    var routes = getPokemonRoutes(pokemonName);
    var parts = [];
    for (var s in routes) {
        var seasonRoutes = routes[s];
        if (!seasonRoutes || !seasonRoutes.length) continue;
        for (var i = 0; i < seasonRoutes.length; i++) {
            var routeName = typeof seasonRoutes[i] === 'string' ? seasonRoutes[i] : seasonRoutes[i].route;
            var hordeSize = typeof seasonRoutes[i] === 'string' ? 5 : (seasonRoutes[i].hordeSize || 5);
            parts.push('<span class="route-chip">' + hordeSize + '× ' + esc(routeName) + '</span>');
        }
    }
    if (parts.length === 0) return '';
    return '<div class="route-chips">' + parts.join('') + '</div>';
}

var NAME_MAP = {
    "nidoran-f": "Nidoran♀",
    "nidoran♀": "Nidoran♀",
    "nidoran-m": "Nidoran♂",
    "nidoran♂": "Nidoran♂",
    "farfetchd": "Farfetch'd",
    "farfetch'd": "Farfetch'd",
    "mr. mime": "Mr. Mime",
    "mime jr.": "Mime Jr.",
    "porygon-z": "Porygon-Z",
    "porygon2": "Porygon2",
    "ho-oh": "Ho-Oh"
};

function displayName(name) {
    if (NAME_MAP[name]) return NAME_MAP[name];
    return name.charAt(0).toUpperCase() + name.slice(1);
}

function getPokemonId(name) {
    return POKEAPI_IDS[name] || "?";
}

function showTargetCard(pokemonName) {
    var existing = document.getElementById('targetCard');
    if (existing) existing.remove();

    var card = document.createElement('div');
    card.id = 'targetCard';
    card.className = 'target-card-overlay';

    var sprite = getShinySpriteUrl(pokemonName);
    var routes = getPokemonRoutes(pokemonName);
    var seasons = getPokemonSeasons(pokemonName);
    var seasonNames = {all:"🌿 Todas", spring:"🌸 Primavera", summer:"☀️ Verano", autumn:"🍂 Otoño", winter:"❄️ Invierno"};

    var html = '<div class="target-card">';
    html += '<button class="target-card-close">✕</button>';
    html += '<div class="target-card-sprite">';
    if (sprite) html += '<img src="' + sprite + '" onerror="this.style.display=\'none\'">';
    html += '</div>';
    html += '<h3 class="target-card-name">' + esc(displayName(pokemonName)) + '</h3>';

    html += '<div class="target-card-seasons">';
    seasons.forEach(function(s) {
        html += '<span class="season-badge season-badge-' + s + '">' + (seasonNames[s]||s) + '</span>';
    });
    html += '</div>';

    html += '<div class="target-card-divider"></div>';

    var hasRoutes = false;
    for (var s in routes) {
        var list = routes[s];
        if (!list || !list.length) continue;
        hasRoutes = true;
        html += '<div class="target-card-season-row"><span class="season-badge season-badge-' + s + '">' + (seasonNames[s]||s) + '</span><span class="target-card-routes">';
        for (var i = 0; i < list.length; i++) {
            var r = typeof list[i] === 'string' ? { route: list[i], time: 'all', chance: 100, hordeSize: 5 } : list[i];
            var timeIcon = r.time === 'all' ? '🔄' : r.time === 'day' ? '☀️' : r.time === 'night' ? '🌙' : '🌅';
            html += '<span class="target-card-route-line">' + timeIcon + ' <strong>' + (r.hordeSize||5) + '×</strong> ' + esc(r.route) + ' <span class="tcr-chance">' + (r.chance||100) + '%</span></span>';
        }
        html += '</span></div>';
    }
    if (!hasRoutes) {
        html += '<p class="target-card-no-routes">Sin rutas registradas</p>';
    }

    html += '</div>';
    card.innerHTML = html;
    document.body.appendChild(card);

    card.addEventListener('click', function(e) {
        if (e.target === card) card.remove();
    });
    card.querySelector('.target-card-close').addEventListener('click', function() { card.remove(); });
}
